import { defineConfig } from "tsup";

export default defineConfig([
  // Configuration for ESM and CJS (unminified)
  {
    entry: ["src/index.ts"],
    clean: true, // Clean only on the first config run
    format: ["esm", "cjs"],
    dts: true, // Generate .d.ts files for ESM/CJS
    sourcemap: true,
    outDir: "dist",
    target: "es2022",
    treeshake: true,
    splitting: true, // Allow splitting for ESM/CJS
    minify: false, // Keep ESM and CJS unminified
  },
  // Configuration for IIFE (minified)
  {
    entry: ["src/index.ts"],
    clean: false, // Don't clean again
    format: ["iife"],
    outExtension() {
      // Use a distinct extension like .iife.min.js
      return {
        js: `.iife.min.js`,
      };
    },
    globalName: "Quantible", // Set the global variable name
    sourcemap: true,
    outDir: "dist",
    target: "es2020", // Target slightly older for broader browser compatibility
    treeshake: true,
    splitting: false, // IIFE usually doesn't benefit from splitting
    minify: true, // Minify the IIFE build
    dts: false, // DTS already generated by the first config
  },
]);
